const BIBLE_DATA = {
    versions: [
        { id: "unv",     n: "和合本",              pinned: true,  lang: "zh",       type: "traditional" },
        { id: "rcuv",    n: "和合修訂版",          pinned: false, lang: "zh",       type: "traditional" },
        { id: "tcv2019", n: "現中2019",            pinned: false, lang: "zh",       type: "modern" },
        { id: "ncv",     n: "新譯本",              pinned: true,  lang: "zh",       type: "modern" },
        { id: "lcc",     n: "呂振中譯本",          pinned: false, lang: "zh",       type: "modern" },
        { id: "ofm",     n: "思高譯本",            pinned: false, lang: "zh",       type: "catholic" },
        { id: "recover", n: "恢復本",              pinned: false, lang: "zh",       type: "modern" },
        { id: "wcb",     n: "環球譯本",            pinned: false, lang: "zh",       type: "modern" },
        { id: "csb",     n: "中文標準譯本",        pinned: false, lang: "zh",       type: "modern" },
        { id: "cbol",    n: "原文直譯",            pinned: false, lang: "original", type: "literal" },
        { id: "tcv95",   n: "現代中文譯本1995",    pinned: false, lang: "zh",       type: "modern" },
        { id: "cnet",    n: "NET聖經中譯本",       pinned: false, lang: "zh",       type: "modern" },
        { id: "cuwv",    n: "文理和合本",          pinned: false, lang: "zh",       type: "traditional" },
        { id: "cnv",     n: "當代譯本",            pinned: false, lang: "zh",       type: "modern" },
        { id: "kjv",     n: "KJV",                 pinned: true,  lang: "en",       type: "traditional" },
        { id: "niv",     n: "NIV",                 pinned: false, lang: "en",       type: "modern" },
        { id: "nasb",    n: "NASB",                pinned: false, lang: "en",       type: "literal" },
        { id: "asv",     n: "ASV",                 pinned: false, lang: "en",       type: "literal" },
        { id: "bbe",     n: "BBE",                 pinned: false, lang: "en",       type: "paraphrase" },
        { id: "web",     n: "WEB",                 pinned: false, lang: "en",       type: "web" },
        { id: "erv",     n: "ERV",                 pinned: false, lang: "en",       type: "easy" },
        { id: "fhlwh",   n: "新約原文",            pinned: false, lang: "original", type: "original" }
    ],
    
    books: [
    // 舊約
    { s: "創",   n: "創世記",     k: "Gen",   c: 50,  g: "舊約" },
    { s: "出",   n: "出埃及記",   k: "Exo",   c: 40,  g: "舊約" },
    { s: "利",   n: "利未記",     k: "Lev",   c: 27,  g: "舊約" },
    { s: "民",   n: "民數記",     k: "Num",   c: 36,  g: "舊約" },
    { s: "申",   n: "申命記",     k: "Deu",   c: 34,  g: "舊約" },
    { s: "書",   n: "約書亞記",   k: "Josh",  c: 24,  g: "舊約" },
    { s: "士",   n: "士師記",     k: "Judg",  c: 21,  g: "舊約" },
    { s: "路",   n: "路得記",     k: "Ruth",  c: 4,   g: "舊約" },
    { s: "撒上", n: "撒母耳記上", k: "1Sam",  c: 31,  g: "舊約" },
    { s: "撒下", n: "撒母耳記下", k: "2Sam",  c: 24,  g: "舊約" },
    { s: "王上", n: "列王紀上",   k: "1Kin",  c: 22,  g: "舊約" },
    { s: "王下", n: "列王紀下",   k: "2Kin",  c: 25,  g: "舊約" },
    { s: "代上", n: "歷代志上",   k: "1Chr",  c: 29,  g: "舊約" },
    { s: "代下", n: "歷代志下",   k: "2Chr",  c: 36,  g: "舊約" },
    { s: "拉",   n: "以斯拉記",   k: "Ezra",  c: 10,  g: "舊約" },
    { s: "尼",   n: "尼希米記",   k: "Neh",   c: 13,  g: "舊約" },
    { s: "斯",   n: "以斯帖記",   k: "Esth",  c: 10,  g: "舊約" },
    { s: "伯",   n: "約伯記",     k: "Job",   c: 42,  g: "舊約" },
    { s: "詩",   n: "詩篇",       k: "Ps",    c: 150, g: "舊約" },
    { s: "箴",   n: "箴言",       k: "Prov",  c: 31,  g: "舊約" },
    { s: "傳",   n: "傳道書",     k: "Eccl",  c: 12,  g: "舊約" },
    { s: "雅",   n: "雅歌",       k: "Song",  c: 8,   g: "舊約" },
    { s: "賽",   n: "以賽亞書",   k: "Isa",   c: 66,  g: "舊約" },
    { s: "耶",   n: "耶利米書",   k: "Jer",   c: 52,  g: "舊約" },
    { s: "哀",   n: "耶利米哀歌", k: "Lam",   c: 5,   g: "舊約" },
    { s: "結",   n: "以西結書",   k: "Ezek",  c: 48,  g: "舊約" },
    { s: "但",   n: "但以理書",   k: "Dan",   c: 12,  g: "舊約" },
    { s: "何",   n: "何西阿書",   k: "Hos",   c: 14,  g: "舊約" },
    { s: "珥",   n: "約珥書",     k: "Joel",  c: 3,   g: "舊約" },
    { s: "摩",   n: "阿摩司書",   k: "Amos",  c: 9,   g: "舊約" },
    { s: "俄",   n: "俄巴底亞書", k: "Obad",  c: 1,   g: "舊約" },
    { s: "拿",   n: "約拿書",     k: "Jonah", c: 4,   g: "舊約" },
    { s: "彌",   n: "彌迦書",     k: "Mic",   c: 7,   g: "舊約" },
    { s: "鴻",   n: "那鴻書",     k: "Nah",   c: 3,   g: "舊約" },
    { s: "哈",   n: "哈巴谷書",   k: "Hab",   c: 3,   g: "舊約" },
    { s: "番",   n: "西番雅書",   k: "Zeph",  c: 3,   g: "舊約" },
    { s: "該",   n: "哈該書",     k: "Hag",   c: 2,   g: "舊約" },
    { s: "亞",   n: "撒迦利亞書", k: "Zech",  c: 14,  g: "舊約" },
    { s: "瑪",   n: "瑪拉基書",   k: "Mal",   c: 4,   g: "舊約" },

    // 新約
    { s: "太",   n: "馬太福音",   k: "Matt",  c: 28,  g: "新約" },
    { s: "可",   n: "馬可福音",   k: "Mark",  c: 16,  g: "新約" },
    { s: "路",   n: "路加福音",   k: "Luke",  c: 24,  g: "新約" },
    { s: "約",   n: "約翰福音",   k: "John",  c: 21,  g: "新約" },
    { s: "徒",   n: "使徒行傳",   k: "Acts",  c: 28,  g: "新約" },
    { s: "羅",   n: "羅馬書",     k: "Rom",   c: 16,  g: "新約" },
    { s: "林前", n: "哥林多前書", k: "1Cor",  c: 16,  g: "新約" },
    { s: "林後", n: "哥林多後書", k: "2Cor",  c: 13,  g: "新約" },
    { s: "加",   n: "加拉太書",   k: "Gal",   c: 6,   g: "新約" },
    { s: "弗",   n: "以斯帖記",   k: "Eph",   c: 6,   g: "新約" },
    { s: "腓",   n: "腓立比書",   k: "Phil",  c: 4,   g: "新約" },
    { s: "歌",   n: "歌羅西書",   k: "Col",   c: 4,   g: "新約" },
    { s: "帖前", n: "帖撒羅尼迦前書", k: "1Thess", c: 5, g: "新約" },
    { s: "帖後", n: "帖撒羅尼迦後書", k: "2Thess", c: 3, g: "新約" },
    { s: "提前", n: "提摩太前書", k: "1Tim",  c: 6,   g: "新約" },
    { s: "提後", n: "提摩太後書", k: "2Tim",  c: 4,   g: "新約" },
    { s: "多",   n: "提多書",     k: "Titus", c: 3,   g: "新約" },
    { s: "門",   n: "腓利門書",   k: "Phlm",  c: 1,   g: "新約" },
    { s: "希",   n: "希伯來書",   k: "Heb",   c: 13,  g: "新約" },
    { s: "雅",   n: "雅各書",     k: "Jas",   c: 5,   g: "新約" },
    { s: "彼前", n: "彼得前書",   k: "1Pet",  c: 5,   g: "新約" },
    { s: "彼後", n: "彼得後書",   k: "2Pet",  c: 3,   g: "新約" },
    { s: "約一", n: "約翰一書",   k: "1John", c: 5,   g: "新約" },
    { s: "約二", n: "約翰二書",   k: "2John", c: 1,   g: "新約" },
    { s: "約三", n: "約翰三書",   k: "3John", c: 1,   g: "新約" },
    { s: "猶",   n: "猶大書",     k: "Jude",  c: 1,   g: "新約" },
    { s: "啟",   n: "啟示錄",     k: "Rev",   c: 22,  g: "新約" }
]
};
